version: "3"
services: 

    portainer-ce:
        image: portainer/portainer-ce
        container_name: "portainer-ce"
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock